# change the command key
unbind C-b
set -g prefix C-a

# need to set this we can set an explicit ctrl-[command key]
bind a send-prefix
bind-key / command-prompt -p "buffer index" "paste-buffer -b %%"
# make tmux use vi keybindings
set-window-option -g mode-keys vi

set-option -g status off

set-option buffer-limit 100

