[tools]
"aqua:atuinsh/atuin" = "latest"
eza = "latest"
fzf = "latest"
go = "1.23.0"
node = "23.11.0"
python = "3.13.3"
rust = "stable"
typst = "latest"
zig = "0.14.0"
zls = "0.14.0"
zoxide = "latest"
