[tools]
"aqua:atuinsh/atuin" = "latest"
bat = "latest"
cmake = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
go = "1.23.0"
lazygit = "latest"
ninja = "latest"
node = "23.11.0"
pre-commit = "latest"
python = "3.13.3"
ripgrep = "latest"
rust = "stable"
typst = "latest"
zoxide = "latest"
